version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "19:35"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 1
    target-branch: master
